# ChoreQuest Production Docker Compose
# Deploys ChoreQuest app only - requires external Supabase instance
#
# Usage: docker compose --env-file .env.production -f docker-compose.prod.yml up -d
#
# Prerequisites:
# 1. Supabase instance running (local CLI, hosted, or self-hosted Docker)
# 2. .env.production configured with Supabase credentials

services:
  # ChoreQuest Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: chorequest-app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Supabase Configuration (from external instance)
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Internal server-side URL (for Docker-to-Docker communication)
      - SUPABASE_INTERNAL_URL=${SUPABASE_INTERNAL_URL:-http://supabase-kong:8000}
      # Cron + auth configuration
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://127.0.0.1:3000}
      - CRON_SECRET=${CRON_SECRET}
      - HOSTNAME=${HOSTNAME_OVERRIDE:-0.0.0.0}
      - HOST=0.0.0.0
      # Database bootstrap toggle
      - ENABLE_DB_BOOTSTRAP=${ENABLE_DB_BOOTSTRAP:-false}
      # Database credentials for migrations (Option C only)
      - DB_HOST=${DB_HOST:-supabase-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}

      # Application Configuration
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    networks:
      - chorequest
      - supabase_default
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Network Configuration
networks:
  chorequest:
    driver: bridge
    name: chorequest_network
  supabase_default:
    external: true
    name: supabase_default
