import { Character, QuestInstance, QuestStatus } from "@/lib/types/database";

export const createMockQuest = (overrides: Partial<QuestInstance> = {}): QuestInstance => ({
  id: "quest-1",
  title: "Test Quest",
  description: "Test Description",
  difficulty: "EASY",
  status: "PENDING" as QuestStatus,
  xp_reward: 100,
  gold_reward: 50,
  category: "DAILY",
  created_by_id: "user-1",
  due_date: null,
  created_at: "2025-01-10",
  updated_at: "2025-01-10",
  recurrence_pattern: null,
  assigned_to_id: null,
  completed_at: null,
  approved_at: null,
  streak_bonus: null,
  streak_count: null,
  volunteer_bonus: null,
  volunteered_by: null,
  template_id: null,
  quest_type: null,
  cycle_start_date: null,
  cycle_end_date: null,
  family_id: "family-1",
  ...overrides,
});

export const baseCharacter: Character = {
  id: "char-1",
  user_id: "user-1",
  name: "Knight Nova",
  class: "KNIGHT",
  level: 1,
  xp: 0,
  gold: 0,
  gems: 0,
  honor_points: 0,
  avatar_url: null,
  created_at: "2025-01-01",
  updated_at: "2025-01-01",
  active_family_quest_id: null,
};
