import type { QuestInstance } from "@/lib/types/database";

export const mockQuests: QuestInstance[] = [
  {
    id: "quest-1",
    family_id: "family-1",
    title: "Clean the kitchen",
    description: "Wash dishes and wipe counters",
    status: "PENDING",
    difficulty: "EASY",
    category: "DAILY",
    xp_reward: 50,
    gold_reward: 10,
    quest_type: "INDIVIDUAL",
    created_by_id: "user-1",
    assigned_to_id: "user-2",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    due_date: null,
    completed_at: null,
    recurrence_pattern: null,
    template_id: null,
    volunteer_bonus: null,
    streak_bonus: null,
    streak_count: null,
    approved_at: null,
    cycle_start_date: null,
    cycle_end_date: null,
    volunteered_by: null,
  },
  {
    id: "quest-2",
    family_id: "family-1",
    title: "Take out trash",
    description: "Empty all trash bins",
    status: "IN_PROGRESS",
    difficulty: "EASY",
    category: "DAILY",
    xp_reward: 25,
    gold_reward: 5,
    quest_type: "INDIVIDUAL",
    created_by_id: "user-1",
    assigned_to_id: "user-2",
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
    due_date: null,
    completed_at: null,
    recurrence_pattern: null,
    template_id: null,
    volunteer_bonus: null,
    streak_bonus: null,
    streak_count: null,
    approved_at: null,
    cycle_start_date: null,
    cycle_end_date: null,
    volunteered_by: null,
  },
  {
    id: "quest-3",
    family_id: "family-1",
    title: "Do homework",
    description: "Complete math and science assignments",
    status: "COMPLETED",
    difficulty: "MEDIUM",
    category: "DAILY",
    xp_reward: 100,
    gold_reward: 20,
    quest_type: "INDIVIDUAL",
    created_by_id: "user-1",
    assigned_to_id: "user-3",
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
    due_date: null,
    completed_at: "2024-01-03T12:00:00Z",
    recurrence_pattern: null,
    template_id: null,
    volunteer_bonus: null,
    streak_bonus: null,
    streak_count: null,
    approved_at: null,
    cycle_start_date: null,
    cycle_end_date: null,
    volunteered_by: null,
  },
  {
    id: "quest-4",
    family_id: "family-1",
    title: "Mow the lawn",
    description: "Cut grass in front and back yard",
    status: "PENDING",
    difficulty: "HARD",
    category: "WEEKLY",
    xp_reward: 200,
    gold_reward: 50,
    quest_type: "FAMILY",
    created_by_id: "user-1",
    assigned_to_id: null,
    created_at: "2024-01-04T00:00:00Z",
    updated_at: "2024-01-04T00:00:00Z",
    due_date: null,
    completed_at: null,
    recurrence_pattern: null,
    template_id: null,
    volunteer_bonus: 0.2,
    streak_bonus: null,
    streak_count: null,
    approved_at: null,
    cycle_start_date: null,
    cycle_end_date: null,
    volunteered_by: null,
  },
];
